config/routes.rb
Rails.application.routes.draw do
  resources :wallets
  devise_for :users

  resources :wallets, only: [:index, :show, :new, :create] do
    get 'sign_out_user'
  end

  root to: 'wallets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  include UuidSetter
  # include PreventDeletion
end

app/models/cif.rb
class Cif < ApplicationRecord
  has_many :users
  before_create -> { set_uuid(self) }
end

app/models/concerns/prevent_deletion.rb
module PreventDeletion
  def delete
    raise ActiveRecord::Rollback
  end

  def destroy
    raise ActiveRecord::Rollback
  end

  def delete_all
    raise ActiveRecord::Rollback
  end

  def destroy_all
    raise ActiveRecord::Rollback
  end
end

app/models/concerns/uuid_setter.rb
module UuidSetter
  def set_uuid(data)
    # define uuid before create to db
    data.id = SecureRandom.uuid
  end
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :users
  before_create -> { set_uuid(self) }
end

app/models/user.rb
class User < ApplicationRecord
  before_create -> { set_uuid(self) }
  after_create :add_demo_balance
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :role, optional: true
  belongs_to :cif, optional: true
  has_many :credits, class_name: 'Wallet', foreign_key: 'sender_user_id', dependent: :destroy
  has_many :debits, class_name: 'Wallet', foreign_key: 'receiver_user_id', dependent: :destroy

  def check_balance
    self.debits.pluck(:amount).compact.sum - self.credits.pluck(:amount).compact.sum
  end

  def add_demo_balance
    demo_balance = Wallet.new(amount: 1_000_000, remark: 'demo_balance', receiver_user_id: self.id)
    demo_balance.save
  end
end

app/models/wallet.rb
class Wallet < ApplicationRecord
  before_create -> { set_uuid(self) }
  validates :amount, presence: true
  validate :sufficent_balance
  validate :positive_amount

  belongs_to :sender_user, :class_name => 'User', dependent: :destroy, optional: true
  belongs_to :receiver_user, :class_name => 'User', dependent: :destroy, optional: true

  def sufficent_balance
    return unless self.sender_user.present?

    if self.amount.to_f > self.sender_user.check_balance.to_f
      errors.add(:amount, "Balance is not enough!")
    end
  end

  def positive_amount
    return if self.amount.to_f > 0
    
    errors.add(:amount, "cannot be 0 or less and must be numeric")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  def redirect_non_user
    redirect_to root_path if current_user.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_non_user
  before_action :set_wallet, only: %i[ show ]
  before_action :set_user_list, only: %i[ new create ]
  before_action :get_transactions, only: %i[ index ]

  # GET /wallets or /wallets.json
  def index
    respond_to do |format|
      format.html { render :index }
      format.json { render json: @credits.as_json }
    end
  end

  # GET /wallets/1 or /wallets/1.json
  def show
  end

  # GET /wallets/new
  def new
    @wallet = Wallet.new
  end

  # POST /wallets or /wallets.json
  def create
    @wallet = Wallet.new(wallet_params)
    @wallet.sender_user_id = current_user.id

    respond_to do |format|
      if @wallet.save
        format.html { redirect_to wallet_url(@wallet), notice: "Wallet was successfully created." }
        format.json { render :show, status: :created, location: @wallet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wallet.errors, status: :unprocessable_entity }
      end
    end
  end

  def sign_out_user
    sign_out current_user

    redirect_to root_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wallet
      @wallet = current_user.credits.find_by(id: params[:id])
      @wallet = current_user.debits.find_by(id: params[:id]) if @wallet.blank?
    end

    # Only allow a list of trusted parameters through.
    def wallet_params
      params.require(:wallet).permit(:amount, :remark, :receiver_user_id, :sender_user_id)
    end

    def set_user_list
      @users = User.where.not(id: current_user.id).order(:email)
    end

    def get_transactions
      @credits = current_user.credits.order(:created_at)
      @debits = current_user.debits.order(:created_at)
      @balance = current_user.check_balance
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Repo
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags

    - if user_signed_in?
      .col-md-12
        strong.pull-right
          = "Logged in as " + current_user.email
      .col-md-12
        = button_to 'Edit profile', edit_user_registration_path, method: 'get', class: 'btn-primary pull-right'
      .col-md-12
        = button_to 'Logout', destroy_user_session_path, method: 'delete', class: 'btn-primary pull-right'
      .col-md-12
    - else
      .col-md-12
        = button_to 'Login', new_user_session_path, class: 'btn-primary pull-right'
  body
    script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"
    = yield

app/views/wallets/_credit.html.erb
<div id="<%= dom_id credit %>">
  <p>
    <strong>Amount:</strong>
    <%= credit.amount %>
  </p>

  <p>
    <strong>Remark:</strong>
    <%= credit.remark %>
  </p>

  <p>
    <strong>Receiver user:</strong>
    <%= credit.receiver_user&.email %>
  </p>

</div>

app/views/wallets/_debit.html.erb
<div id="<%= dom_id debit %>">
  <p>
    <strong>Amount:</strong>
    <%= debit.amount %>
  </p>

  <p>
    <strong>Remark:</strong>
    <%= debit.remark %>
  </p>

  <p>
    <strong>Sender user:</strong>
    <%= debit.sender_user&.email %>
  </p>

</div>

app/views/wallets/_form.html.erb
<%= form_with(model: wallet) do |form| %>
  <% if wallet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(wallet.errors.count, "error") %> prohibited this wallet from being saved:</h2>

      <ul>
        <% wallet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <label style="display: block" for="wallet_amount">
      Amount <t style="color:red;">*</t>
    </label>
      
    <%= form.text_field :amount, required: true %>
  </div>

  <div class="col-md-12" style="padding:5px"> </div>

  <div>
    <%= form.label :remark, style: "display: block" %>
    <%= form.text_field :remark %>
  </div>

  <div class="col-md-12" style="padding:5px"> </div>

  <div>
    <label style="display: block" for="wallet_amount">
      Receiver User <t style="color:red;">*</t>
    </label>

    <%= form.collection_select :receiver_user_id, @users, :id, :email, required: true %>
  </div>

  <div class="col-md-12" style="padding:5px"> </div>

  <div>
    <%= form.submit 'Submit Transaction' %>
  </div>
<% end %>

<script>
  $(document).on("input", "#wallet_amount", function() {this.value = this.value.replace(/\D/g,'');});
</script>

app/views/wallets/_wallet.html.erb
<div id="<%= dom_id wallet %>">
  <p>
    <strong>Amount:</strong>
    <%= wallet.amount %>
  </p>

  <p>
    <strong>Remark:</strong>
    <%= wallet.remark %>
  </p>

  <p>
    <strong>Receiver user:</strong>
    <%= wallet.receiver_user&.email %>
  </p>

  <p>
    <strong>Sender user:</strong>
    <%= wallet.sender_user&.email %>
  </p>

</div>

app/views/wallets/edit.html.erb
<div class='col-md-12'>
  <h1>Editing wallet</h1>

  <%= render "form", wallet: @wallet %>

  <br>

  <div>
    <%= link_to "Show this wallet", @wallet %> |
    <%= link_to "Back to wallets", wallets_path %>
  </div>
</div>

app/views/wallets/index.html.erb
<p style="color: green"><%= notice %></p>

<div class='col-md-12'>
  <%= button_to "New Transaction", new_wallet_path, method: :get, class: 'btn-primary pull-left' %>
</div>

<div class='col-md-12'>
  <h2>
    Your Balance:
    <%= @balance %>
  </h2>
</div>

<div class='col-md-12'>
  <h2>Transaction List</h2>
</div>

<div class='col-md-12'>
  <h2>Credits</h1>
  <div id="credits">
    <% @credits.each do |credit| %>
      <div class='col-md-3'>
        <%= render credit %>
        <p>
          <%= link_to "Show this transaction", credit %>
        </p>
      </div>
    <% end %>
  </div>
</div>


<div class='col-md-12'>
  <h2>Debits</h1>
  <div id="debits">
    <% @debits.each do |debit| %>
      <div class='col-md-3'>
        <%= render debit %>
        <p>
          <%= link_to "Show this transaction", debit %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/wallets/new.html.erb
<div class='col-md-12'>
  <h1>New transaction</h1>

  <%= render "form", wallet: @wallet %>

  <br>

  <div>
    <%= link_to "Back to wallets", wallets_path %>
  </div>
</div>

app/views/wallets/show.html.erb
<div class='col-md-12'>
  <p style="color: green"><%= notice %></p>

  <%= render @wallet %>

  <div>
    <%= link_to "Back to transaction list", wallets_path %>
  </div>
</div>